# create password with echo -n 'TheM0$stAmaz1ngP@s$W0rdOfThatFuckkkingW0rld' | base64
apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secrets
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: NjMyNWI4NmIzMzQ1ZTBiZDBjOWIxOGJiM2I3NDE5NWVkYTA3ZmE1MmQyOTY5
  MYSQL_PASSWORD: YXplcnR5MTIzNCAzNDU2