apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
          # valueFrom:
          #     configMapKeyRef:
          #      name: wordpress-configmap
          #      key: mysql_hostname
        - name: WORDPRESS_DB_NAME
          valueFrom:
              configMapKeyRef:
               name: wordpress-configmap
               key: mysql_dbname
        - name: WORDPRESS_DB_USER
          valueFrom:
              configMapKeyRef:
               name: wordpress-configmap
               key: mysql_username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-db-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
